package cobraerr

// Parse attempts to parse a string error generated by Cobra into one of the
// following error structs:
//
// - [InvalidFlagError]
// - [UnknownCommandError]
// - [UnknownFlagError]
func Parse(err error) error {
	if err, ok := ParseInvalidFlagError(err); ok {
		return err
	}
	if err, ok := ParseUnknownFlagError(err); ok {
		return err
	}
	if err, ok := ParseUnknownCommandError(err); ok {
		return err
	}

	return err
}
